/*
SFTPGo

SFTPGo allows to securely share your files over SFTP, HTTP and optionally FTP/S and WebDAV as well. Several storage backends are supported and they are configurable per user, so you can serve a local directory for a user and an S3 bucket (or part of it) for another one. SFTPGo also supports virtual folders, a virtual folder can use any of the supported storage backends. So you can have, for example, an S3 user that exposes a GCS bucket (or part of it) on a specified path and an encrypted local filesystem on another one. Virtual folders can be private or shared among multiple users, for shared virtual folders you can define different quota limits for each user. SFTPGo allows to create HTTP/S links to externally share files and folders securely, by setting limits to the number of downloads/uploads, protecting the share with a password, limiting access by source IP address, setting an automatic expiration date. 

API version: 2.2.2-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// WebDAVBinding struct for WebDAVBinding
type WebDAVBinding struct {
	// TCP address the server listen on
	Address *string `json:"address,omitempty"`
	// the port used for serving requests
	Port *int32 `json:"port,omitempty"`
	EnableHttps *bool `json:"enable_https,omitempty"`
	// 1 means that client certificate authentication is required in addition to HTTP basic authentication
	ClientAuthType *int32 `json:"client_auth_type,omitempty"`
}

// NewWebDAVBinding instantiates a new WebDAVBinding object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebDAVBinding() *WebDAVBinding {
	this := WebDAVBinding{}
	return &this
}

// NewWebDAVBindingWithDefaults instantiates a new WebDAVBinding object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebDAVBindingWithDefaults() *WebDAVBinding {
	this := WebDAVBinding{}
	return &this
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *WebDAVBinding) GetAddress() string {
	if o == nil || o.Address == nil {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebDAVBinding) GetAddressOk() (*string, bool) {
	if o == nil || o.Address == nil {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *WebDAVBinding) HasAddress() bool {
	if o != nil && o.Address != nil {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *WebDAVBinding) SetAddress(v string) {
	o.Address = &v
}

// GetPort returns the Port field value if set, zero value otherwise.
func (o *WebDAVBinding) GetPort() int32 {
	if o == nil || o.Port == nil {
		var ret int32
		return ret
	}
	return *o.Port
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebDAVBinding) GetPortOk() (*int32, bool) {
	if o == nil || o.Port == nil {
		return nil, false
	}
	return o.Port, true
}

// HasPort returns a boolean if a field has been set.
func (o *WebDAVBinding) HasPort() bool {
	if o != nil && o.Port != nil {
		return true
	}

	return false
}

// SetPort gets a reference to the given int32 and assigns it to the Port field.
func (o *WebDAVBinding) SetPort(v int32) {
	o.Port = &v
}

// GetEnableHttps returns the EnableHttps field value if set, zero value otherwise.
func (o *WebDAVBinding) GetEnableHttps() bool {
	if o == nil || o.EnableHttps == nil {
		var ret bool
		return ret
	}
	return *o.EnableHttps
}

// GetEnableHttpsOk returns a tuple with the EnableHttps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebDAVBinding) GetEnableHttpsOk() (*bool, bool) {
	if o == nil || o.EnableHttps == nil {
		return nil, false
	}
	return o.EnableHttps, true
}

// HasEnableHttps returns a boolean if a field has been set.
func (o *WebDAVBinding) HasEnableHttps() bool {
	if o != nil && o.EnableHttps != nil {
		return true
	}

	return false
}

// SetEnableHttps gets a reference to the given bool and assigns it to the EnableHttps field.
func (o *WebDAVBinding) SetEnableHttps(v bool) {
	o.EnableHttps = &v
}

// GetClientAuthType returns the ClientAuthType field value if set, zero value otherwise.
func (o *WebDAVBinding) GetClientAuthType() int32 {
	if o == nil || o.ClientAuthType == nil {
		var ret int32
		return ret
	}
	return *o.ClientAuthType
}

// GetClientAuthTypeOk returns a tuple with the ClientAuthType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebDAVBinding) GetClientAuthTypeOk() (*int32, bool) {
	if o == nil || o.ClientAuthType == nil {
		return nil, false
	}
	return o.ClientAuthType, true
}

// HasClientAuthType returns a boolean if a field has been set.
func (o *WebDAVBinding) HasClientAuthType() bool {
	if o != nil && o.ClientAuthType != nil {
		return true
	}

	return false
}

// SetClientAuthType gets a reference to the given int32 and assigns it to the ClientAuthType field.
func (o *WebDAVBinding) SetClientAuthType(v int32) {
	o.ClientAuthType = &v
}

func (o WebDAVBinding) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Address != nil {
		toSerialize["address"] = o.Address
	}
	if o.Port != nil {
		toSerialize["port"] = o.Port
	}
	if o.EnableHttps != nil {
		toSerialize["enable_https"] = o.EnableHttps
	}
	if o.ClientAuthType != nil {
		toSerialize["client_auth_type"] = o.ClientAuthType
	}
	return json.Marshal(toSerialize)
}

type NullableWebDAVBinding struct {
	value *WebDAVBinding
	isSet bool
}

func (v NullableWebDAVBinding) Get() *WebDAVBinding {
	return v.value
}

func (v *NullableWebDAVBinding) Set(val *WebDAVBinding) {
	v.value = val
	v.isSet = true
}

func (v NullableWebDAVBinding) IsSet() bool {
	return v.isSet
}

func (v *NullableWebDAVBinding) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebDAVBinding(val *WebDAVBinding) *NullableWebDAVBinding {
	return &NullableWebDAVBinding{value: val, isSet: true}
}

func (v NullableWebDAVBinding) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebDAVBinding) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


