/*
SFTPGo

SFTPGo allows to securely share your files over SFTP, HTTP and optionally FTP/S and WebDAV as well. Several storage backends are supported and they are configurable per user, so you can serve a local directory for a user and an S3 bucket (or part of it) for another one. SFTPGo also supports virtual folders, a virtual folder can use any of the supported storage backends. So you can have, for example, an S3 user that exposes a GCS bucket (or part of it) on a specified path and an encrypted local filesystem on another one. Virtual folders can be private or shared among multiple users, for shared virtual folders you can define different quota limits for each user. SFTPGo allows to create HTTP/S links to externally share files and folders securely, by setting limits to the number of downloads/uploads, protecting the share with a password, limiting access by source IP address, setting an automatic expiration date. 

API version: 2.2.2-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// QuotaScan struct for QuotaScan
type QuotaScan struct {
	// username to which the quota scan refers
	Username *string `json:"username,omitempty"`
	// scan start time as unix timestamp in milliseconds
	StartTime *int64 `json:"start_time,omitempty"`
}

// NewQuotaScan instantiates a new QuotaScan object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuotaScan() *QuotaScan {
	this := QuotaScan{}
	return &this
}

// NewQuotaScanWithDefaults instantiates a new QuotaScan object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuotaScanWithDefaults() *QuotaScan {
	this := QuotaScan{}
	return &this
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *QuotaScan) GetUsername() string {
	if o == nil || o.Username == nil {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuotaScan) GetUsernameOk() (*string, bool) {
	if o == nil || o.Username == nil {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *QuotaScan) HasUsername() bool {
	if o != nil && o.Username != nil {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *QuotaScan) SetUsername(v string) {
	o.Username = &v
}

// GetStartTime returns the StartTime field value if set, zero value otherwise.
func (o *QuotaScan) GetStartTime() int64 {
	if o == nil || o.StartTime == nil {
		var ret int64
		return ret
	}
	return *o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuotaScan) GetStartTimeOk() (*int64, bool) {
	if o == nil || o.StartTime == nil {
		return nil, false
	}
	return o.StartTime, true
}

// HasStartTime returns a boolean if a field has been set.
func (o *QuotaScan) HasStartTime() bool {
	if o != nil && o.StartTime != nil {
		return true
	}

	return false
}

// SetStartTime gets a reference to the given int64 and assigns it to the StartTime field.
func (o *QuotaScan) SetStartTime(v int64) {
	o.StartTime = &v
}

func (o QuotaScan) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Username != nil {
		toSerialize["username"] = o.Username
	}
	if o.StartTime != nil {
		toSerialize["start_time"] = o.StartTime
	}
	return json.Marshal(toSerialize)
}

type NullableQuotaScan struct {
	value *QuotaScan
	isSet bool
}

func (v NullableQuotaScan) Get() *QuotaScan {
	return v.value
}

func (v *NullableQuotaScan) Set(val *QuotaScan) {
	v.value = val
	v.isSet = true
}

func (v NullableQuotaScan) IsSet() bool {
	return v.isSet
}

func (v *NullableQuotaScan) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuotaScan(val *QuotaScan) *NullableQuotaScan {
	return &NullableQuotaScan{value: val, isSet: true}
}

func (v NullableQuotaScan) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuotaScan) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


