apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dcu-device-plugin-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: dcu-dp-ds
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        name: dcu-dp-ds
    spec:
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
      nodeSelector:
        hardware-type: HYGONDCU
      containers:
        - image: swr.cn-south-1.myhuaweicloud.com/openioctopus/dcu-plugin:v1.7.0
          name: dcu-dp-cntr
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: dp
              mountPath: /var/lib/kubelet/device-plugins
            - name: sys
              mountPath: /sys
            - name: dev
              mountPath: /dev
      volumes:
        - name: dp
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: sys
          hostPath:
            path: /sys
        - name: dev
          hostPath:
            path: /dev
